name: alpine-judge-dispatcher

languages:
  c:
    versions:
      - c99
      - c11
      - c17

  cpp:
    versions:
      - c++11
      - c++17
      - c++20

  go:
    versions:
      - go1.24
      - go1.26

  java:
    versions:
      - java14
      - java16

  python:
    versions:
      - python3.10
      - python3.12

runners:
  - runner-001
  - runner-002